# Generated by Django 6.0.2 on 2026-02-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientorder',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
