# Generated by Django 6.0.2 on 2026-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_price_per_serving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_by_slice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemingredient',
            name='measurement_type',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters'), ('units', 'units')], max_length=10),
        ),
    ]
