# Generated by Django 6.0.2 on 2026-02-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_sold_by_slice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsold',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
